### ISSUE TITLE
update desperately needed

### ISSUE THREAD

**Issue by kajott** [framefield/tooll_operators#1]
The repository is severely outdated. Normally, this wouldn't be a problem, as there's a more recent set of operators in the 0.3.1 binary release. Unfortunately, https://github.com/framefield/tooll/commit/af0666c1 requires changes in some operators that aren't publicized anywhere and aren't easy to reproduce for outside users.

Phrased differently, **there's currently no public source of an Operators directory that works with the current develop branch of the Tooll GitHub repo** (unless I'm missing something).

Is it possible to update this repository to a current set of operators? (Or, alternatively, release a working build of 0.3.3?)

**Comment by drcynic** [comment]
Hi, I'll update it to a working state on the weekend. Probably I don't have the time to add all new operators that have been developed in the meantime. But getting it back to working state should be no problem.

**Comment by kajott** [comment]
That's highly appreciated. Thanks in advance!

**Comment by pixtur** [comment]
Thanks for this comment. I will also try to help.

**Comment by drcynic** [comment]
ok, I added the missing ops to tooll_operators:master and updated the ones that had to be adapted. I also merged tooll:develop into tooll:master and updated the operator reference of tooll:master to this latest tooll_operator:master version. 
Keyj, I did a short verification test by cloning everything clean and there it worked, but if you encounter some problems let me know.

**Comment by kajott** [comment]
Awesome! I can't check it right now, but I'll do so on Sunday.

**Comment by kajott** [comment]
Looks fine. The camera operators now work again with the newer Tooll code.
From my point of view, it's OK to close the issue now.

**Comment by drcynic** [comment]
Alright, closing it. Somewhere in the near future we will also update the public operators with the latest state.
